steps:
  - id: 'Delete old Docker images'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -ceux
      - |
        gcloud artifacts docker images list ${_IMAGE_NAME} --include-tags --filter="TAGS!=latest" --format="value(DIGEST)" | xargs -n1 -I{} gcloud artifacts docker images delete --quiet --async ${_IMAGE_NAME}@{}

  - id: 'Build Docker image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',  'NOTION_API_SECRET=${_NOTION_API_SECRET}',
        '--build-arg',  'DATABASE_ID=${_DATABASE_ID}',
        '--build-arg',  'INDEX_PAGE_ID=${_INDEX_PAGE_ID}',
        '--build-arg',  'SUBSCRIPTION_PAGE_ID=${_SUBSCRIPTION_PAGE_ID}',
        '--build-arg',  'NEXT_PUBLIC_URL=${_NEXT_PUBLIC_URL}',
        '--build-arg',  'NEXT_PUBLIC_GA_TRACKING_ID=${_NEXT_PUBLIC_GA_TRACKING_ID}',
        '-t',           '${_IMAGE_NAME}',
        '--cache-from', '${_IMAGE_NAME}:latest',
        '.',
      ]

  - id: 'Push Docker image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}']

  - id: 'Deploy to Cloud Run'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        '${_SERVICE_NAME}',
        '--image',  '${_IMAGE_NAME}',
        '--region', '${_REGION}',
      ]

substitutions:
  _REGION: asia-northeast1
  _REPOSITORY: alpacat
  _SERVICE_NAME: notion-blog
  _IMAGE_NAME: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}'
  _NEXT_PUBLIC_URL: ''
  _NEXT_PUBLIC_GA_TRACKING_ID: ''

availableSecrets:
  secretManager:
  - versionName: 'projects/${PROJECT_ID}/secrets/NOTION_API_SECRET/versions/latest'
    env: _NOTION_API_SECRET
  - versionName: 'projects/${PROJECT_ID}/secrets/DATABASE_ID/versions/latest'
    env: _DATABASE_ID
  - versionName: 'projects/${PROJECT_ID}/secrets/INDEX_PAGE_ID/versions/latest'
    env: _INDEX_PAGE_ID
  - versionName: 'projects/${PROJECT_ID}/secrets/SUBSCRIPTION_PAGE_ID/versions/latest'
    env: _SUBSCRIPTION_PAGE_ID

options:
  dynamic_substitutions: true

timeout: 900s

images:
  - '${_IMAGE_NAME}'
