name: Deploy

on:
  schedule:
    - cron: '5 23 * * 0' # 08:05(Mon) JST
  workflow_dispatch:

jobs:
  curl:
    name: Deploy on Monday(JST)
    runs-on: ubuntu-latest

    steps:
    - name: curl
      run: curl -X POST '${{ secrets.DEPLOY_HOOK_URL }}'
