name: Deploy

on:
  schedule:
    - cron: '5 22 * * 0' # 07:05(Mon) JST
  workflow_dispatch:

jobs:
  curl:
    name: Kick deploy hook
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: curl -X POST '${{ secrets.DEPLOY_HOOK_URL }}'
