name: Deploy

on:
  schedule:
    - cron: '5 23 * * 0' # 08:05(Mon) JST

jobs:
  curl:
    name: Deploy on Monday(JST)
    runs-on: ubuntu-latest

    steps:
    - name: curl
      env:
        DEPLOY_HOOK_URL: ${{secrets.DEPLOY_HOOK_URL}}
      uses: wei/curl@v1
      with:
        args: -X POST "$DEPLOY_HOOK_URL"
